library(haven)
library(readxl)
library(dplyr)
library(stringr)
library(panelr)
library(plm)
library(plyr)
library(circlize)
library(reshape2)
library(writexl)
library(ggplot2)
library(psych)
library(usmap)
library(maps)
library(ggridges)

basedir = paste0(dirname(dirname(rstudioapi::getSourceEditorContext()$path)), "/")
datadir = paste0(basedir, "Data/")
tabdir = paste0(basedir, "Output/Tables/")
figdir = paste0(basedir, "Output/Figures/")