---
title: "7. Figure A.1.2. Location of respondents"
---

```{r}
source('helpers.R')

# Determine state respondents of Study 1
df1 = subset(read.csv(paste0(datadir, 's1_survey_long.csv')), wave == 1)
df1$state = tolower(str_trim(df1$state, "right"))

df1 = aggregate(wave ~ state, data = df1, FUN = length)
colnames(df1) = c("state", "N")

# Determine state respondents of Study 2
df2 = subset(read.csv(paste0(datadir, 's2_survey_long.csv')), wave == 1)
zips = read.csv(paste0(datadir, "zips.csv"))
zips$zip = as.character(zips$zip)

df2 = merge(df2, zips, by = "zip", all = FALSE)
df2$state = tolower(state.name[match(df2$state,state.abb)])

df2 = aggregate(wave ~ state, data = df2, FUN = length)
colnames(df2) = c("state", "N")
```

Map location respondents Study 1
```{r}
state = map_data("state")
state$N = as.numeric(NA)
for (i in c(1:nrow(state))){
  if (state$region[i] %in% df1$state){
    state$N[i] = df1$N[which(df1$state == state$region[i])]
  }
}

ggplot(data=state, aes(x=long, y=lat, fill=N, group=group)) + 
  geom_polygon(color = "white") + 
  guides(fill=FALSE) + 
  scale_fill_continuous(high = "#132B43", low = "#56B1F7", na.value="grey90") + 
  theme_void() + 
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), 
        axis.ticks.x=element_blank(), axis.title.y=element_blank(), 
        axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
  coord_fixed(1.3)

ggsave(paste0(figdir, "Figure A.1.2. Location of respondents Study 1.png"), 
       height = 10, width = 20)
```

Map location respondents Study 2
```{r}
state = map_data("state")
state$N = as.numeric(NA)
for (i in c(1:nrow(state))){
  if (state$region[i] %in% df2$state){
    state$N[i] = df2$N[which(df2$state == state$region[i])]
  }
}

ggplot(data=state, aes(x=long, y=lat, fill=N, group=group)) + 
  geom_polygon(color = "white") + 
  guides(fill=FALSE) + 
  scale_fill_continuous(high = "#132B43", low = "#56B1F7", na.value="grey90") + 
  theme_void() + 
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), 
        axis.ticks.x=element_blank(), axis.title.y=element_blank(), 
        axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
  coord_fixed(1.3)

ggsave(paste0(figdir, "Figure A.1.2. Location of respondents Study 2.png"), 
       height = 10, width = 20)
```

